<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use App\Enums\VehicleCategory;
use App\Enums\VehicleStatus;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            // ===== Operasional Harian (15) =====
            [
                'name' => 'Mitsubishi Expander',
                'plate_number' => 'B 2094 UYN',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(180)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(365)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(200)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(165)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian',
            ],
            [
                'name' => 'Toyota Avanza',
                'plate_number' => 'B 2386 UYV',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(20)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(300)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(100)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(265)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian',
            ],
            [
                'name' => 'Mitsubishi Expander',
                'plate_number' => 'B 2668 UYZ',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(90)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(280)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(150)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(215)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian',
            ],
            [
                'name' => 'Mitsubishi Expander',
                'plate_number' => 'B 2684 UYP',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(45)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(200)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(120)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(245)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian',
            ],
            [
                'name' => 'Mitsubishi Expander',
                'plate_number' => 'B 1860 DKG',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::InUse->value,
                'tax_expiry' => Carbon::now()->addDays(300)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(420)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(250)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(115)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian — sedang dipakai',
            ],
            [
                'name' => 'Toyota Velloz',
                'plate_number' => 'B 1181 DKO',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->subDays(5)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(90)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(300)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(65)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian — pajak sudah habis',
            ],
            [
                'name' => 'Toyota Avanza',
                'plate_number' => 'B 1856 ROZ',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(60)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(320)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(80)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(285)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian',
            ],
            [
                'name' => 'Toyota Rush',
                'plate_number' => 'B 1137 VZB',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(10)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(150)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(180)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(185)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian — pajak segera habis',
            ],
            [
                'name' => 'Toyota Avanza',
                'plate_number' => 'B 1776 RYA',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(200)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(380)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(90)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(275)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian',
            ],
            [
                'name' => 'Toyota Avanza',
                'plate_number' => 'B 1601 RZQ',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Maintenance->value,
                'tax_expiry' => Carbon::now()->addDays(120)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(260)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(210)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(155)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian — sedang maintenance',
            ],
            [
                'name' => 'Toyota Avanza',
                'plate_number' => 'B 2753 UYO',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(75)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(310)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(60)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(305)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian',
            ],
            [
                'name' => 'Mitsubishi Expander',
                'plate_number' => 'B 1421 DKU',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(25)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(190)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(170)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(195)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian',
            ],
            [
                'name' => 'Mitsubishi Expander',
                'plate_number' => 'B 1574 DOD',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->subDays(15)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(60)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(280)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(85)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian — pajak sudah habis',
            ],
            [
                'name' => 'Mitsubishi Expander',
                'plate_number' => 'B 2189 UZD',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(150)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(340)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(110)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(255)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian',
            ],
            [
                'name' => 'Suzuki XL7',
                'plate_number' => 'B 2144 UYI',
                'category' => VehicleCategory::OperationalDaily->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(55)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(270)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(140)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(225)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional harian',
            ],

            // ===== Project (12) =====
            [
                'name' => 'Toyota Innova',
                'plate_number' => 'BG 1896 NH',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(100)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(290)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(160)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(205)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project',
            ],
            [
                'name' => 'Toyota Hilux',
                'plate_number' => 'B 9420 UBC',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(120)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(250)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(150)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(215)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project',
            ],
            [
                'name' => 'Toyota Hilux',
                'plate_number' => 'B 9118 UBE',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::InUse->value,
                'tax_expiry' => Carbon::now()->addDays(80)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(230)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(190)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(175)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project — sedang dipakai',
            ],
            [
                'name' => 'Mitsubishi Expander',
                'plate_number' => 'B 1080 DOF',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(40)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(210)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(220)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(145)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project',
            ],
            [
                'name' => 'Toyota Innova',
                'plate_number' => 'DK 1992 ACG',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(170)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(360)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(70)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(295)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project',
            ],
            [
                'name' => 'Mitsubishi Triton',
                'plate_number' => 'BG 8587 GD',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Maintenance->value,
                'tax_expiry' => Carbon::now()->addDays(90)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(200)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(180)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(185)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project — sedang maintenance',
            ],
            [
                'name' => 'Mitsubishi Triton',
                'plate_number' => 'BG 8340 CG',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(35)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(180)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(200)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(165)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project',
            ],
            [
                'name' => 'Toyota Avanza',
                'plate_number' => 'B 1576 RZE',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(110)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(240)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(130)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(235)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project',
            ],
            [
                'name' => 'Toyota Innova Zenix Non Hybrid',
                'plate_number' => 'B 2191 UYX',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(65)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(330)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(100)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(265)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project',
            ],
            [
                'name' => 'Toyota Innova Zenix',
                'plate_number' => 'B 1893 DYE',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->subDays(10)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(75)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(260)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(105)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project — pajak sudah habis',
            ],
            [
                'name' => 'Honda BRV',
                'plate_number' => 'B 1727 RYA',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(130)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(350)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(85)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(280)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project',
            ],
            [
                'name' => 'Toyota Avanza',
                'plate_number' => 'B 1069 RZC',
                'category' => VehicleCategory::Project->value,
                'status' => VehicleStatus::Unavailable->value,
                'tax_expiry' => Carbon::now()->subDays(30)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->subDays(10)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(320)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->subDays(20)->format('Y-m-d'),
                'contract_company' => 'PT BKI Project',
                'description' => 'Mobil project — kontrak & pajak sudah habis',
            ],

            // ===== Operasional Struktural (7) =====
            [
                'name' => 'Toyota Innova Zenix',
                'plate_number' => 'B 1083 VZH',
                'category' => VehicleCategory::OperationalStructural->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(250)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(400)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(50)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(315)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional struktural',
            ],
            [
                'name' => 'Honda BRV',
                'plate_number' => 'B 1625 RZF',
                'category' => VehicleCategory::OperationalStructural->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(15)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(180)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(220)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(145)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional struktural — pajak segera habis',
            ],
            [
                'name' => 'Honda BRV',
                'plate_number' => 'B 1231 RZF',
                'category' => VehicleCategory::OperationalStructural->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(95)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(270)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(160)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(205)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional struktural',
            ],
            [
                'name' => 'Honda BRV',
                'plate_number' => 'B 1290 RZD',
                'category' => VehicleCategory::OperationalStructural->value,
                'status' => VehicleStatus::InUse->value,
                'tax_expiry' => Carbon::now()->addDays(70)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(220)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(190)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(175)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional struktural — sedang dipakai',
            ],
            [
                'name' => 'Honda HRV',
                'plate_number' => 'B 1036 RYB',
                'category' => VehicleCategory::OperationalStructural->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(140)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(300)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(110)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(255)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional struktural',
            ],
            [
                'name' => 'Honda HRV',
                'plate_number' => 'B 1907 DZC',
                'category' => VehicleCategory::OperationalStructural->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->subDays(8)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(50)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(290)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(75)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional struktural — pajak sudah habis',
            ],
            [
                'name' => 'Toyota Innova Zenix',
                'plate_number' => 'B 1353 VZO',
                'category' => VehicleCategory::OperationalStructural->value,
                'status' => VehicleStatus::Available->value,
                'tax_expiry' => Carbon::now()->addDays(200)->format('Y-m-d'),
                'stnk_expiry' => Carbon::now()->addDays(380)->format('Y-m-d'),
                'contract_date' => Carbon::now()->subDays(75)->format('Y-m-d'),
                'contract_expiry' => Carbon::now()->addDays(290)->format('Y-m-d'),
                'contract_company' => 'PT BKI',
                'description' => 'Mobil operasional struktural',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::firstOrCreate(
                ['plate_number' => $vehicle['plate_number']],
                collect($vehicle)->except('plate_number')->toArray()
            );
        }
    }
}
